### ISSUE TITLE
Unable to start due to unknown error

### ISSUE THREAD

**Issue by Aqualie** [synzen/Discord.RSS-Web#4]
Trying to start Discord.RSS-Web fails with below without any useful log indicating what could be the problem here. 
```
/app/src $ npm start

> discord.rss-web@0.0.1 start /app
> node server.js

[2020-05-24 13:56:01] INFO : [W] Attempting to connect to databases...
[2020-05-24 13:56:01] INFO : [WM] Connected to MongoDB
[2020-05-24 13:56:01] INFO : [WM] Connected to Redis
[2020-05-24 13:56:01] INFO : [W] Databases connected. Spawning shards...
[2020-05-24 13:56:01] FATAL: [WM]
    size: 0
    timeout: 0
[2020-05-24 13:56:01] WARN : [WM] pino.final with prettyPrint does not support flushing
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord.rss-web@0.0.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discord.rss-web@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-05-24T13_56_02_000Z-debug.log
/app/src $ vi /home/node/.npm/_logs/2020-05-24T13_56_02_000Z-debug.log
/app/src $ cat /home/node/.npm/_logs/2020-05-24T13_56_02_000Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle discord.rss-web@0.0.1~prestart: discord.rss-web@0.0.1
6 info lifecycle discord.rss-web@0.0.1~start: discord.rss-web@0.0.1
7 verbose lifecycle discord.rss-web@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle discord.rss-web@0.0.1~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle discord.rss-web@0.0.1~start: CWD: /app
10 silly lifecycle discord.rss-web@0.0.1~start: Args: [ '-c', 'node server.js' ]
11 silly lifecycle discord.rss-web@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle discord.rss-web@0.0.1~start: Failed to exec start script
13 verbose stack Error: discord.rss-web@0.0.1 start: `node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid discord.rss-web@0.0.1
15 verbose cwd /app/src
16 verbose Linux 4.19.84-1.ph3-esx
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v12.16.3
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error discord.rss-web@0.0.1 start: `node server.js`
22 error Exit status 1
23 error Failed at the discord.rss-web@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by synzen** [comment]
Note that only developers should be using this repo, not users. If you are a user, please refer to the docs linked on the README  https://docs.discordrss.xyz/setting-up/web-interface for instructions on properly running the web app as a user using the [correct repo](https://github.com/synzen/Discord.RSS-Clone). This clone repo to ensure the correct versions are used between the bot and the web at all times.

Regarding your issue, errors should be more verbose now concerning login issues. Typically it's because you hit a rate limit, or your token is invalid
