### ISSUE TITLE
Web is sometimes started but sometimes not

### ISSUE THREAD

**Issue by jannyba** [synzen/Discord.RSS-Web#9]
Hi

when I reboot my VPS web is sometimes working sometimes not, here is something from logs:
I'm starting discordrss with crontab
`@reboot /usr/bin/node /home/Dragy/discord.rss/bot-web.js`
when web is working:
```
{"level":30,"time":1597607354930,"tag":"W","msg":"Attempting to connect to databases..."}
{"level":30,"time":1597607354975,"tag":"WM","msg":"Connected to MongoDB"}
{"level":30,"time":1597607355036,"tag":"WM","msg":"Connected to Redis"}
{"level":30,"time":1597607355042,"tag":"W","msg":"Databases connected"}
{"level":30,"time":1597607356102,"tag":"-","msg":"Connected to Redis"}
{"level":30,"time":1597607356806,"tag":"-","msg":"Discord.RSS-Web logged in as abcd#1234"}
{"level":30,"time":1597607356835,"tag":"0","msg":"Listeners registered"}
{"level":30,"time":1597607356865,"tag":"0","msg":"Redis initialized"}
{"level":30,"time":1597607356875,"tag":"W","msg":"HTTP UI listening on port 28699!"}
{"level":30,"time":1597607356875,"tag":"W","msg":"HTTPS UI listening on port 28701!"}

mongod    696  mongodb   10u  IPv4  17151      0t0  TCP 127.0.0.1:27017 (LISTEN)
sshd      728     root    3u  IPv4  16795      0t0  TCP *:44222 (LISTEN)
sshd      728     root    4u  IPv6  16806      0t0  TCP *:44222 (LISTEN)
node      729     root   40u  IPv6  17650      0t0  TCP *:28699 (LISTEN)
node      729     root   41u  IPv6  17651      0t0  TCP *:28701 (LISTEN)
redis-ser 744    redis    6u  IPv4  16937      0t0  TCP 127.0.0.1:6379 (LISTEN)
redis-ser 744    redis    7u  IPv6  16938      0t0  TCP [::1]:6379 (LISTEN)
```
and web is not working
```
{"level":50,"time":1597610088786,"tag":"-","error":{"type":"Error","message":"Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","stack":"Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)","errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6379},"msg":"Redis database encountered error"}
{"level":50,"time":1597610088791,"tag":"WM","error":{"type":"Error","message":"Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","stack":"Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)","errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6379},"msg":"Redis database encountered error"}
{"level":50,"time":1597610089131,"tag":"-","error":{"type":"Error","message":"Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","stack":"Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)","errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6379},"msg":"Redis database encountered error"}
{"level":50,"time":1597610089134,"tag":"WM","error":{"type":"Error","message":"Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","stack":"Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)","errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6379},"msg":"Redis database encountered error"}
{"level":50,"time":1597610089712,"tag":"-","error":{"type":"Error","message":"Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","stack":"Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)","errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6379},"msg":"Redis database encountered error"}
{"level":50,"time":1597610089714,"tag":"WM","error":{"type":"Error","message":"Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","stack":"Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)","errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6379},"msg":"Redis database encountered error"}
{"level":30,"time":1597610114706,"tag":"W","msg":"Attempting to connect to databases..."}
{"level":30,"time":1597610114737,"tag":"WM","msg":"Connected to MongoDB"}
{"level":30,"time":1597610114770,"tag":"WM","msg":"Connected to Redis"}
{"level":30,"time":1597610114776,"tag":"W","msg":"Databases connected"}
{"level":30,"time":1597610115719,"tag":"-","msg":"Connected to Redis"}
{"level":30,"time":1597610116487,"tag":"-","msg":"Discord.RSS-Web logged in as abcd#1234"}

mongod     684  mongodb   10u  IPv4  17138      0t0  TCP 127.0.0.1:27017 (LISTEN)
sshd       717     root    3u  IPv4  16798      0t0  TCP *:44222 (LISTEN)
sshd       717     root    4u  IPv6  16809      0t0  TCP *:44222 (LISTEN)
apache2    721     root    4u  IPv6  16776      0t0  TCP *:28702 (LISTEN)
apache2    723 www-data    4u  IPv6  16776      0t0  TCP *:28702 (LISTEN)
apache2    724 www-data    4u  IPv6  16776      0t0  TCP *:28702 (LISTEN)
redis-ser  785    redis    6u  IPv4  16936      0t0  TCP 127.0.0.1:6379 (LISTEN)
redis-ser  785    redis    7u  IPv6  16937      0t0  TCP [::1]:6379 (LISTEN)
```

**Comment by synzen** [comment]
Hi,

Other people have reported the same issue (usually when it's their first time starting the bot). From past reports, it resolves itself after a while (about a day) and no longer happens again.

If you can provide a reproducible example where it consistently happens, then I can take a look. But unfortunately I have not had any reproducible examples to work with. Some random approaches you may take are rebooting, reinstalling/recloning, reinstalling node, or waiting a while.

**Comment by jannyba** [comment]
II will send you email with ssh to the server, thanks.

**Comment by synzen** [comment]
Please provide the requested details. By reproducible example, I mean the full steps to reproduce the issue from having no files to cloning, the configs you put in, how you started the app, and any other detail you can possibly add. Expecting me to go into your personal server and fix everything without any details is neither reasonable nor transparent for anyone else who faces the same issues.

**Comment by jannyba** [comment]
I'm not asking you to go and fix my server, but to provide reproducible example that probably means I need start VPS over and write here every command line I entered?

if you login to my server where you can d oanything (I created snapshot with server provider) you can find issue quicker and then fix it in the source codes.

I wrote message to you via discord, thanks.

**Comment by synzen** [comment]
> 
> 
> I'm not asking you to go and fix my server, but to provide reproducible example that probably means I need start VPS over and write here every command line I entered?
> 

Yes. The issue must be reproducible irrespective of their environment. If I cannot reproduce it, then I can only assume it's related to something specific to your environment.

Again, I suggest waiting 24-48 hours to see if it resolves itself.

**Comment by jannyba** [comment]
I see this in the error logs:
{"level":50,"time":1597692884465,"tag":"-","error":{"type":"Error","message":"Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","stack":"Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)","errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6379},"msg":"Redis database encountered error"}
{"level":50,"time":1597692884470,"tag":"WM","error":{"type":"Error","message":"Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","stack":"Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)","errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6379},"msg":"Redis database encountered error"}
{"level":50,"time":1597692884810,"tag":"-","error":{"type":"Error","message":"Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","stack":"Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)","errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6379},"msg":"Redis database encountered error"}
{"level":50,"time":1597692884815,"tag":"WM","error":{"type":"Error","message":"Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","stack":"Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)","errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6379},"msg":"Redis database encountered error"}
{"level":50,"time":1597692885390,"tag":"-","error":{"type":"Error","message":"Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","stack":"Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)","errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6379},"msg":"Redis database encountered error"}
{"level":50,"time":1597692885395,"tag":"WM","error":{"type":"Error","message":"Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","stack":"Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)","errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6379},"msg":"Redis database encountered error"}

```
701:C 17 Aug 2020 21:35:06.264 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
701:C 17 Aug 2020 21:35:06.266 # Redis version=5.0.3, bits=64, commit=00000000, modified=0, pid=701, just started
701:C 17 Aug 2020 21:35:06.267 # Configuration loaded
 762:M 17 Aug 2020 21:35:06.320 # Server initialized
762:M 17 Aug 2020 21:35:06.328 * DB loaded from disk: 0.007 seconds
762:M 17 Aug 2020 21:35:06.328 * Ready to accept connections
```
maybe you can change the code to continuously try connect to redis every 5 seconds on startup and on lost connection?

**Comment by synzen** [comment]
When you see multiple Redis connection errors, that means its reattempting to connect.

**Comment by synzen** [comment]
> 
> 
> Here is the trace logging. It may be related to an API limit, but I'm not entirely sure. Restarting the bot several times sometimes will result in starting in an expected way.
> 
> ```
> Aug 22 23:23:23 buster systemd[1]: Started MonitoRSS web.
> Aug 22 23:23:24 buster monitorss-web[6142]: [2020-08-22 23:23:24.797 +0000] INFO : [W] Attempting to connect to databases...
> Aug 22 23:23:24 buster monitorss-web[6142]: [2020-08-22 23:23:24.894 +0000] INFO : [WM] Connected to MongoDB
> Aug 22 23:23:24 buster monitorss-web[6142]: [2020-08-22 23:23:24.899 +0000] INFO : [WM] Connected to Redis
> Aug 22 23:23:24 buster monitorss-web[6142]: [2020-08-22 23:23:24.905 +0000] INFO : [W] Databases connected
> Aug 22 23:23:24 buster monitorss-web[6142]: [2020-08-22 23:23:24.905 +0000] DEBUG: [W] Flushing redis
> Aug 22 23:23:24 buster monitorss-web[6142]: [2020-08-22 23:23:24.912 +0000] DEBUG: [W] Redis successfully flushed, spawning shards
> Aug 22 23:23:25 buster monitorss-web[6142]: [2020-08-22 23:23:25.612 +0000] INFO : [-] Connected to Redis
> Aug 22 23:23:26 buster monitorss-web[6142]: [2020-08-22 23:23:26.180 +0000] INFO : [-] Discord.RSS-Web logged in as rss-testenv#5471
> Aug 22 23:23:26 buster monitorss-web[6142]: [2020-08-22 23:23:26.181 +0000] DEBUG: [0] Waiting for client to be ready...
> ```
> 
> The ansible-playbook is here: https://github.com/Ultima1252/MonitoRSS-ansible
> 
> If you want to adopt it feel free, it still needs a bit of work, but the core functionality is there. I'm likely not going to maintain it as I have too many other things on my plate.

I've not used Ansible before, but its worth taking a look. Thanks for taking the time to create the repo.

**Comment by Ultima1252** [comment]
No problem, I will improve the README to make it a bit easier to jump in. I wrote it for a friend to make migrations to another server almost entirely automated. I used a lot of best practices for security for everything except Mongodb (I don't know Mongodb at all). I suspect that mongodb needs to be configured a bit more than what I did for it to be secure.

**Comment by synzen** [comment]
> everything

Great to hear, no problem, I'm sure I'll figure it out and might as well learn something new in the process. I will see if the issue can be pinned down when I get the time - if it can be, then I'll close this issue with the fix.

**Comment by TheSpad** [comment]
I'm seeing the same thing (with Docker), doesn't seem to matter how long I leave it or how many times I restart the container, it just hangs on 
```
DEBUG: [0] Waiting for client to be ready...
```
If there's any useful information or tests I can do for you to try and diagnose it, please let me know.
